### ISSUE TITLE
Unable to find OpenHardwareMonitorReport.exe

### ISSUE THREAD

**Issue by bobbolous** [nobodysu/zabbix-mini-IPMI#11]
Unfortunately I am not able to find the OpenHardwareMonitorReport.exe in any version of the OpenHardwareMonitor. Neither on their GitHub ([https://github.com/openhardwaremonitor/openhardwaremonitor](url)) nor their website ([http://openhardwaremonitor.org/](url)). Any suggestions?

**Comment by nobody43** [comment]
https://github.com/nobodysu/zabbix-mini-IPMI#choosing-ohmr-version
https://github.com/openhardwaremonitor/openhardwaremonitor/files/1130239/OpenHardwareMonitorReport.zip
