### ISSUE TITLE
ZBX_NOTSUPPORTED: Unsupported item key.

### ISSUE THREAD

**Issue by AdmiraalA** [nobodysu/zabbix-mini-IPMI#20]
Even though i've  installed this following the directions is get abovementioned error while testing.
Server : Ubuntu 18.04 , Zabbix 3.4.11
Monitored host : Debian 9 , Zabbix-agent 3.4.11

Please help

**Comment by AdmiraalA** [comment]
Never mind , this was caused by misconfiguration on the default Debian zabbix-agent package..

**Comment by nobody43** [comment]
on client:
grep Include /etc/zabbix/zabbix_agentd.conf
pwd userparameter_mini-ipmi2.conf
systemctl restart zabbix-agent.service

anywhere:
zabbix_get -s 192.0.2.1 -k mini.cputemp.discovery[getverb,"Example host"]
zabbix_get -s 192.0.2.1 -k mini.disktemp.discovery[getverb,"Example host"]

**Comment by nobody43** [comment]
Good. :)

**Comment by AdmiraalA** [comment]
Already made a Bugreport for that as well
