### ISSUE TITLE
issue with discovery?

### ISSUE THREAD

**Issue by killmasta93** [nobodysu/zabbix-mini-IPMI#39]
Hi,
the CPU temperature does not appear as in the discovery rule it shows this error see picture

![Screenshot from 2019-12-13 11-32-59](https://user-images.githubusercontent.com/13953629/70815908-6122dd80-1d9c-11ea-9f1f-43155e9b45ad.png)

Thank you

**Comment by nobody43** [comment]
I need a full error output e.g. `./mini_ipmi_lmsensors.py get NON` and `sensors -u` output.

**Comment by nobody43** [comment]
You should try new version also: https://github.com/nobodysu/zabbix-mini-IPMI/pull/38

**Comment by killmasta93** [comment]
Thanks for the reply, this is what i get 
root@prometheus4:/etc/zabbix/scripts# ./mini_ipmi_lmsensors.py get NON
Traceback (most recent call last):
  File "./mini_ipmi_lmsensors.py", line 272, in <module>
    getOutput_Out = getOutput()
  File "./mini_ipmi_lmsensors.py", line 68, in getOutput
    pSplit = p.strip()
AttributeError: 'NoneType' object has no attribute 'strip'

as for the update i installed it around 4 days ago

Thank you

**Comment by nobody43** [comment]
lmsensors not installed? Fix incoming.

**Comment by killmasta93** [comment]
So it seems i needed to install 
sudo apt-get install lm-sensors
after that i ran root@prometheus4:/etc/zabbix/scripts# ./mini_ipmi_lmsensors.py get NON

root@prometheus4:/etc/zabbix/scripts# ./mini_ipmi_lmsensors.py get NON
{
    "data": [
        {
            "{#CPU}": 0
        },
        {
            "{#CORE}": "0",
            "{#CPUC}": 0
        },
        {
            "{#CORE}": "1",
            "{#CPUC}": 0
        },
        {
            "{#CORE}": "2",
            "{#CPUC}": 0
        },
        {
            "{#CORE}": "3",
            "{#CPUC}": 0
        }
    ]
}

I guess i need to wait till it refreshes on zabbix

**Comment by killmasta93** [comment]
after a while im seeing the data coming that was it needed to install lm sensors

**Comment by killmasta93** [comment]
just a quick question, as for the temperature threshold is it possible to change it? or is it possible to change it for certain hosts?

**Comment by nobody43** [comment]
I'm referring to lmsensors in the [latest version](https://github.com/nobodysu/zabbix-mini-IPMI/tree/cpu_refactoring).
Tjmax could not be changed.
In the template there are a `Macros` tab for global thresholds.
In specific host there are `Macros - Inherited and host macros` section for host-specific thresholds.

**Comment by killmasta93** [comment]
Thank you for the quick reply, i ended up changing it on the trigger section which says 

  | {Template mini-IPMI v2:mini.disk.temp[MAX].last(500)}>46
-- | --
i changed the value to 52
