### ISSUE TITLE
Permissions graphs as guest ? 

### ISSUE THREAD

**Issue by nicolasgoudard** [nobodysu/zabbix-mini-IPMI#44]
Hello. Sorry, I don't know If it is a bug or not. When I connect as "guest user" to the zabbix interface , nothing is displayed in the temperature graph (no datas). When I connect in "normal" user administrator it is ok, I have datas.
In the guest user group, the guest group has access to everything in read only
How can I repair it ? Maybe I mistake a permission somewhere in the interface ? 

Thanks in advance
Cordially 

[
<img width="1073" alt="Capture d’écran 2020-02-09 à 17 16 03" src="https://user-images.githubusercontent.com/6792673/74105680-539d9000-4b60-11ea-8a72-ff5a0ad8add2.png">
<img width="1073" alt="Capture d’écran 2020-02-09 à 17 17 20" src="https://user-images.githubusercontent.com/6792673/74105681-54cebd00-4b60-11ea-9e36-3e1b5a0253b6.png">

](url)

**Comment by nobody43** [comment]
Administration - User groups - Guest - Permissions

**Comment by nicolasgoudard** [comment]
I empty the caches and it works now.
