### ISSUE TITLE
change trigger temperature treshold

### ISSUE THREAD

**Issue by nicolasgoudard** [nobodysu/zabbix-mini-IPMI#45]
Hello
I want to change the tresholds for each host before having alerts on my zabbix map
The map tell that the temperature is too high( over 60° ) but my sensors on Dell servers specifications tell that the critical threshold is over 92 (different on each node)
sample :
\# sensors
Core 0:        +57.0°C  (high = +82.0°C, crit = +92.0°C)

How can I do ? (I am newbie in zabbix configuration and I don't know where I can change the variable $CPU.HIGH.TEMP on each node)
thx u in advance
Best regards

 - OS: CentOS 8.1
 - Zabbix server version:  4.4.5
 
<img width="521" alt="Capture d’écran 2020-02-10 à 22 22 20" src="https://user-images.githubusercontent.com/6792673/74191450-e23f0980-4c53-11ea-9e97-5c59416ca860.png">

**Comment by nobody43** [comment]
Global: All templates/Template mini-IPMI v2 -> Macros
Per-host: host -> Macros -> Inherited

Critical is a throttling temperature and have it's own trigger.
`$CPU.HIGH.TEMP` is there to take action beforehand. (it's not `high = +82.0°C`)

**Comment by nicolasgoudard** [comment]
Ok, thanks you, it is working now
