### ISSUE TITLE
Disk temperature too low

### ISSUE THREAD

**Issue by nicolasgoudard** [nobodysu/zabbix-mini-IPMI#46]
Mini ipmi tell the temperature is too low for 20 degrees Celsius on my Poweredge R940 for my disk raid (bus_0_megaraid_1) but the specifications tell that 20 degrees is ok.
How can I change the threshold ? I don't find it in the macros. When I look the configuration I don't see about a threshold. When I ignore the problem, it goes again. Can you help me ? Best regards

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/6792673/74886048-63df1780-5377-11ea-98c2-099a458ed574.png">
<img width="519" alt="image" src="https://user-images.githubusercontent.com/6792673/74886071-79544180-5377-11ea-9603-9d347906dc31.png">
<img width="680" alt="image" src="https://user-images.githubusercontent.com/6792673/74886238-e23bb980-5377-11ea-8d8f-55adbeaebc00.png">

**Comment by nobody43** [comment]
Right now it's hardcoded in the script: https://github.com/nobodysu/zabbix-mini-IPMI/blob/master/mini_ipmi_smartctl.py#L33

**Comment by nicolasgoudard** [comment]
yes thanks you. It is perfectly working
