### ISSUE TITLE
"Unexpected BIOS firmware version" Trigger meaning

### ISSUE THREAD

**Issue by girlpunk** [nobodysu/zabbix-mini-IPMI#49]
**Describe the problem**
Can anyone give more information on what the "Unexpected BIOS firmware version" trigger is reporting? I've had this alert show up for a Windows PC today, but can't find what problem it's actually trying to tell me about.

**To Reproduce**
Unknown

**Expected behavior**
Unknown

**Screenshots**
![image](https://user-images.githubusercontent.com/161093/80804239-744c1380-8bac-11ea-9865-8e84892b33e5.png)

**Please complete the following information:**
 - OS: Windows 10
 - Zabbix server version: 4.4
 - Active or passive check: Passive
 - Using zabbix proxy: No

**Comment by nobody43** [comment]
It's intended to place the list of BIOS versions on your network in `{$EXPECTED.BIOS.VERS}` macro inside template. This way you'll know (by maintaining the list of newest ones) when machines are outdated and needing a BIOS update.

**Comment by nobody43** [comment]
Hope that's resolved.
