### ISSUE TITLE
Как отправляются данные?

### ISSUE THREAD

**Issue by anshibanov** [nobodysu/zabbix-mini-IPMI#56]
ПРи autodiscovery создаются элементы данные с типом zabbix trapper - т.е. что-то должно в эти item слать данные. По логике это должен быть какой-то скрипт в планировщике, но в reame ни слова об этом. Подскажите, пожалуйста, как item должны получать данные?

**Comment by anshibanov** [comment]
@nobodysu help plz

**Comment by nobody43** [comment]
Эти данные шлет sender_wrapper.py - обёртка для zabbix_sender. wrapper выполняется через 80 секунд после discovery.
После прохождения по шагам README все должно работать.

**Comment by anshibanov** [comment]
Спасибо, всё получилось
