### ISSUE TITLE
Changing temp threshold  on only one host?

### ISSUE THREAD

**Issue by killmasta93** [nobodysu/zabbix-mini-IPMI#57]
Hi,
I was wondering if its possible to change the threshold only for one Host? i tried checking on triggers to change but couldn't find the option 

Thank you

**Comment by nobody43** [comment]
Disks or cpus? Linux or Windows?

**Comment by killmasta93** [comment]
thanks for the reply, only CPUs

**Comment by nobody43** [comment]
_Host_ -> Macros -> Inherited -> Change

**Comment by killmasta93** [comment]
thanks for the reply, i went to that section but did not see anything of mini IPMI temps
![image](https://user-images.githubusercontent.com/13953629/87327947-61ce4e80-c4fa-11ea-8103-1ae665cc54ec.png)

**Comment by nobody43** [comment]
Means template is not assigned to the host.

**Comment by killmasta93** [comment]
i checked and it is assigned

![image](https://user-images.githubusercontent.com/13953629/87359635-d078cf80-c52d-11ea-8c90-f80de0444a6a.png)

**Comment by nobody43** [comment]
Then template is not up to date:
https://github.com/nobodysu/zabbix-mini-IPMI/blob/master/Template_mini-IPMI_v2.xml

**Comment by killmasta93** [comment]
thanks for the reply, i tried updating the template by adding and i get this should i remove all the checks on "create"
![image](https://user-images.githubusercontent.com/13953629/87491440-bf06f480-c60d-11ea-9232-a4469aed7e0f.png)

**Comment by killmasta93** [comment]
after checking it did make the changes thank you

**Comment by killmasta93** [comment]
quick question forgot to mention if i would want to do the same for the disk temp?

**Comment by nobody43** [comment]
Right now it's in the file: https://github.com/nobodysu/zabbix-mini-IPMI/blob/master/mini_ipmi_smartctl.py#L32
Will be moved to macro someday.

**Comment by killmasta93** [comment]
Thanks for the reply, so this would apply to all hosts if changing the .py? possible to change on the template for all hosts

**Comment by nobody43** [comment]
On every host there is a copy of `mini_ipmi_smartctl.py` with separate thresholds. Therefore, it's all per-host and cannot be changed through template, yet.
However, I advice you to think twice before changing disk thresholds because it's based on Goggle research: http://www.buildcomputers.net/hdd-temperature.html

**Comment by killmasta93** [comment]
Thank you again, your right ill keep that in mind
