### ISSUE TITLE
Cpu temp shows double

### ISSUE THREAD

**Issue by killmasta93** [nobodysu/zabbix-mini-IPMI#60]
Hi,
Currently after updating the new template, getting to show double CPU not sure why?
Also on the older  template it would alert me the temperature that it was at 
currently only alert me saying its over 65 C and not showing the alert on the temperature that it is at
Thank you 
![image](https://user-images.githubusercontent.com/13953629/88488617-f81b5f00-cf53-11ea-8b8a-87de98114cbc.png)

**Comment by nobody43** [comment]
Global trigger is disabled by default in the template: https://github.com/nobodysu/zabbix-mini-IPMI/blob/master/Template_mini-IPMI_v2.xml#L3279

**Comment by killmasta93** [comment]
thanks for the quick reply, so this is the reason im not getting the current temperature of the alert?
and what about the double CPU alert?

**Comment by nobody43** [comment]
Just disable `CPU temperature is too high` in the template.

Last value in trigger name is moved to comments because it's a bad practice and can mess up triggers in latest versions of zabbix.

**Comment by killmasta93** [comment]
So i would disable one of the cpu temperature is too high, but there is two 
![image](https://user-images.githubusercontent.com/13953629/88489153-3e72bd00-cf58-11ea-907e-f408416368ee.png)

![image](https://user-images.githubusercontent.com/13953629/88489166-55191400-cf58-11ea-9d41-4e5ebd930a04.png)

**Comment by nobody43** [comment]
First one.

**Comment by killmasta93** [comment]
thank you that did the trick so the alert of the  current temperature not possible? or can i enable it on the template?

**Comment by nobody43** [comment]
You could, but it's strongly discouraged - it could break reporting for these problems. Now `last value` is hidden in problem details.
