### ISSUE TITLE
Invalid discovery rule value

### ISSUE THREAD

**Issue by Adam0097** [nobodysu/zabbix-mini-IPMI#61]
I m new in this zabbix world and I am trying to upload the template to my test server to verify that it works, I still encounter a problem with "Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: ' 'python' is not recognized as an internal or external command,
operable program or batch file. '"after uploading the template and assigning it to the host, Python is installed, as well as OpenHardwareMonitorReport, smartools as well, scripts placed (with path configure) in the Zabbix Agent folder

![image](https://user-images.githubusercontent.com/33184484/89169890-26fe8a00-d57f-11ea-8c50-aabd364ed599.png)

![image](https://user-images.githubusercontent.com/33184484/89170635-3b8f5200-d580-11ea-90ca-8e66ebfe6623.png)

![image](https://user-images.githubusercontent.com/33184484/89171512-95dce280-d581-11ea-8cd0-959489f9a356.png)

 - OS Server: OcentOs OS Agent:Windows
 - Zabbix server version: 5.0
 - Using zabbix proxy: No proxy

**Comment by nobody43** [comment]
Python is not in `PATH` apparently. Here's how it can be solved:
https://github.com/nobodysu/zabbix-mini-IPMI/blob/master/screenshots/python-installation1.png
https://github.com/nobodysu/zabbix-mini-IPMI/blob/master/screenshots/python-installation2.png
Reboot is required afterwards.

**Comment by Adam0097** [comment]
in theory worked, but it only managed to throw such errors in the info

![image](https://user-images.githubusercontent.com/33184484/89181973-03463e80-d595-11ea-8e59-a0aec6a1112c.png)

and no data collecting

![image](https://user-images.githubusercontent.com/33184484/89182018-178a3b80-d595-11ea-870f-1a7bade3036c.png)

**Comment by nobody43** [comment]
These errors are expected and data should be there by now.
Provide outputs if not:
https://github.com/nobodysu/zabbix-mini-IPMI#testing

**Comment by Adam0097** [comment]
From client
![image](https://user-images.githubusercontent.com/33184484/89286563-bc1e8300-d652-11ea-8276-0acf1b5ac9b1.png)

**Comment by Adam0097** [comment]
Fixed, next error
![image](https://user-images.githubusercontent.com/33184484/89287966-259f9100-d655-11ea-9c36-3fedcd2c27b2.png)

**Comment by nobody43** [comment]
Are you running the test from admin console (right mouse button -> run as admin)?
Please post the server query - it will tell more.

**Comment by Adam0097** [comment]
The problem seems to be solved, I removed the port adress from ServerActive in config file and it worked !

![image](https://user-images.githubusercontent.com/33184484/89300297-47564380-d668-11ea-9930-61f35fb39868.png)
