### ISSUE TITLE
How one changes the Threshold values?

### ISSUE THREAD

**Issue by kovaga** [nobodysu/zabbix-mini-IPMI#62]
**Describe the problem**
The Disk critical and maximum threshold values are set at 60 and 45 respectively. Is it possible to change them somehow?

**Please complete the following information:**
 - OS: Ubuntu 20.04
 - Zabbix server version: 5.0
 - Using zabbix proxy: No proxy

**Comment by nobody43** [comment]
You can do it here: https://github.com/nobodysu/zabbix-mini-IPMI/blob/master/mini_ipmi_smartctl.py#L32
But it's not recommended cause it's a sane default based on Google research.

**Comment by kovaga** [comment]
Thanks! Silly me, I was looking for the thresholds value within the zabbix template setting etc. but didn't think of looking into the script codes itself.  I know about the safe recommendations, but one of the hdds temp is changing within the 44-46C corridor constantly tripping the alert, so its either increasing the threshold or disabling it altogether for me.
