### ISSUE TITLE
Tutorial configuration template

### ISSUE THREAD

**Issue by SAVAMforWIN** [nobodysu/zabbix-mini-IPMI#68]
hi guys, i'm new to the zabbix world, i'm trying to configure this template but i can't, i'm definitely doing something wrong, is it possible to have a tutorial on how to configure agent side and zabbix side this template?

 - OS: Win 10
 - Zabbix server version: 5.4
 - Using zabbix proxy: No proxy

**Comment by nobody43** [comment]
1. Install the agent: https://www.zabbix.com/download_agents
2. Follow other steps: https://github.com/nobodysu/zabbix-mini-IPMI#windows
3. Upload `Template_mini-IPMI_v2.xml` in web interface: Configuration -> Templates
4. Assign it to the host
5. Watch for results in `Latest data`
