### ISSUE TITLE
Introduce zabbix-mini-IPMI with Windows 10

### ISSUE THREAD

**Issue by Manero-Taube-Monica** [nobodysu/zabbix-mini-IPMI#70]
I have followed all the steps to implement the configuration but it does not work. Maybe it is because I have a Windows 10 on my client. Do you know if it could work on Windows 10? the hardwaremonitor application makes queries. Maybe it is the python script that is not working properly. I hope you can help me and guide me. Best regards.

**Comment by nobody43** [comment]
I need some time to test it on win10. Could you post your outputs as mentioned in
https://github.com/nobodysu/zabbix-mini-IPMI#testing

**Comment by Manero-Taube-Monica** [comment]
The output on my client W10
![Captura de pantalla (133)](https://user-images.githubusercontent.com/56246926/149511704-7c359ed3-00b7-4f87-81f0-d4819444c23d.png)

python 3.10 version
OHM 0.9.2 version
Windows10  10.0.19044 version

**Comment by nobody43** [comment]
Hmm, could you post your OHMR output also? (omitting the serials)
`> OpenHardwareMonitorReport.exe > ohmr.txt`

**Comment by jpaulickcz** [comment]
Here's mine: [ohmr.txt](https://github.com/nobodysu/zabbix-mini-IPMI/files/7979362/ohmr.txt).

However it seems to work just fine on Windows 10 for me. (Just looked in here out of curiosity)

![windows 10 cmd](https://user-images.githubusercontent.com/34006554/151993096-970ef33c-56ee-4e1f-8865-da88b507a5e9.jpg)

**Comment by nobody43** [comment]
Tested with everything. Unable to reproduce.
